// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about_index from "./routes/about/index.tsx";
import * as $api_auth_register from "./routes/api/auth/register.ts";
import * as $api_certifications from "./routes/api/certifications.ts";
import * as $api_contact from "./routes/api/contact.ts";
import * as $api_experiences from "./routes/api/experiences.ts";
import * as $api_hackathons from "./routes/api/hackathons.ts";
import * as $api_languages from "./routes/api/languages.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_researchs from "./routes/api/researchs.ts";
import * as $certifications_certification_ from "./routes/certifications/[certification].tsx";
import * as $certifications_index from "./routes/certifications/index.tsx";
import * as $contact_index from "./routes/contact/index.tsx";
import * as $experiences_experience_ from "./routes/experiences/[experience].tsx";
import * as $experiences_index from "./routes/experiences/index.tsx";
import * as $hackathons_hackathon_ from "./routes/hackathons/[hackathon].tsx";
import * as $hackathons_index from "./routes/hackathons/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $logout from "./routes/logout.ts";
import * as $projects_project_ from "./routes/projects/[project].tsx";
import * as $projects_index from "./routes/projects/index.tsx";
import * as $register_index from "./routes/register/index.tsx";
import * as $researchs_research_ from "./routes/researchs/[research].tsx";
import * as $researchs_index from "./routes/researchs/index.tsx";
import * as $CertificationsCarousel from "./islands/CertificationsCarousel.tsx";
import * as $CertificationsFilter from "./islands/CertificationsFilter.tsx";
import * as $ContactForm from "./islands/ContactForm.tsx";
import * as $ExperiencesTabs from "./islands/ExperiencesTabs.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $HackathonsTimeline from "./islands/HackathonsTimeline.tsx";
import * as $HomeInteractive from "./islands/HomeInteractive.tsx";
import * as $InteractivePaper from "./islands/InteractivePaper.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $ProjectsList from "./islands/ProjectsList.tsx";
import * as $ResearchsAccordion from "./islands/ResearchsAccordion.tsx";
import * as $ScrollAnimation from "./islands/ScrollAnimation.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import * as $auth_LoginPage from "./islands/auth/LoginPage.tsx";
import * as $auth_RegisterPage from "./islands/auth/RegisterPage.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about/index.tsx": $about_index,
    "./routes/api/auth/register.ts": $api_auth_register,
    "./routes/api/certifications.ts": $api_certifications,
    "./routes/api/contact.ts": $api_contact,
    "./routes/api/experiences.ts": $api_experiences,
    "./routes/api/hackathons.ts": $api_hackathons,
    "./routes/api/languages.ts": $api_languages,
    "./routes/api/login.ts": $api_login,
    "./routes/api/researchs.ts": $api_researchs,
    "./routes/certifications/[certification].tsx":
      $certifications_certification_,
    "./routes/certifications/index.tsx": $certifications_index,
    "./routes/contact/index.tsx": $contact_index,
    "./routes/experiences/[experience].tsx": $experiences_experience_,
    "./routes/experiences/index.tsx": $experiences_index,
    "./routes/hackathons/[hackathon].tsx": $hackathons_hackathon_,
    "./routes/hackathons/index.tsx": $hackathons_index,
    "./routes/index.tsx": $index,
    "./routes/login/index.tsx": $login_index,
    "./routes/logout.ts": $logout,
    "./routes/projects/[project].tsx": $projects_project_,
    "./routes/projects/index.tsx": $projects_index,
    "./routes/register/index.tsx": $register_index,
    "./routes/researchs/[research].tsx": $researchs_research_,
    "./routes/researchs/index.tsx": $researchs_index,
  },
  islands: {
    "./islands/CertificationsCarousel.tsx": $CertificationsCarousel,
    "./islands/CertificationsFilter.tsx": $CertificationsFilter,
    "./islands/ContactForm.tsx": $ContactForm,
    "./islands/ExperiencesTabs.tsx": $ExperiencesTabs,
    "./islands/Footer.tsx": $Footer,
    "./islands/HackathonsTimeline.tsx": $HackathonsTimeline,
    "./islands/HomeInteractive.tsx": $HomeInteractive,
    "./islands/InteractivePaper.tsx": $InteractivePaper,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/ProjectsList.tsx": $ProjectsList,
    "./islands/ResearchsAccordion.tsx": $ResearchsAccordion,
    "./islands/ScrollAnimation.tsx": $ScrollAnimation,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
    "./islands/auth/LoginPage.tsx": $auth_LoginPage,
    "./islands/auth/RegisterPage.tsx": $auth_RegisterPage,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
